"use client";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import TopBar from "@/components/TopBar";
import BottomBar from "@/components/BottomBar";
import Footer from "@/components/Footer";
import ScrollUp from "@/components/ScrollUp";
import Metadata from "@/components/MetaData";


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <Metadata title="Portfolio" description="Generated by Nour Alagha" />
      <head />
      <body className={`flex h-full dark:bg-black bg-zinc-50 sm:px-8`}>
        <ThemeProvider attribute="class">
          <div className="relative px-4 lg:px-8 mx-auto w-full max-w-7xl">
            <div className="dark:bg-zinc-900 bg-white relative px-4 sm:px-8 lg:px-12 pt-36 border-[1px] border-y-transparent border-x-zinc-100 dark:border-x-g1 min-h-full">
              <div className="mx-auto max-w-2xl lg:max-w-5xl">
                <TopBar />
                {children}
                <ScrollUp />
                <Footer />
                <BottomBar />
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
